services:
  - type: web
    name: hrms-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "python manage.py shell < create_test_data.py && gunicorn config.wsgi:application"
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: hrms-db
    databaseName: hrms_db
    user: hrms_user
    plan: free
